### ISSUE TITLE
Question about Algorithm 2 in paper

### ISSUE THREAD

**Issue by nicolaihaeni** [jsxzs/SA4D#2]
Hi

I read your work with great interest and have a question regarding the two-stage refinement process. You mentioned in the paper that the first step is to remove outliers, similar to Gaussian Grouping and SAGA, however, I could not find any reference in their paper for this procedure (or their code, for that matter). Could you give some details on how exactly you remove these outliers? Just to be clear, I am referring to the following line in algorithm 2: 
![image](https://github.com/user-attachments/assets/a072c16d-14cb-4776-b9aa-7e5e75890f1e)

Thanks

**Comment by jsxzs** [comment]
Thank you for your interest in my work. The first step, removing outliers, can be found in the paper and code of Gaussian Grouping and SAGA. 
![image](https://github.com/user-attachments/assets/304e6042-ee47-46d3-a96f-88660db547c0)
![image](https://github.com/user-attachments/assets/6375f860-25a4-4874-847e-144b3d2604a3)
